#!/bin/bash
  
 while [ "$1" != "" ]; do
    case $1 in
        -c | --count )           shift
                                x=$1
                                ;;
        -s | --shape )         usage
				b=$2
                                ;;  
  esac
    shift
done 
  for((i=0;i<=x;i++))
  do
   for((k=0;k<x-i;k++))
do
  echo -n  " "
done
    for((j=1;j<=2*i-1;j++))
    do
    echo -n  "$b"
    done
  echo ""
  done
